import type { AuditResult } from './runArk';

const STATUS_EMOJI: Record<string, string> = {
  pass: '✅',
  warn: '⚠️',
  fail: '❌',
};

function scoreEmoji(score: number, maxScore: number): string {
  const pct = maxScore > 0 ? score / maxScore : 0;
  if (pct >= 0.8) return '🟢';
  if (pct >= 0.5) return '🟡';
  return '🔴';
}

function overallEmoji(score: number): string {
  if (score >= 80) return '🟢';
  if (score >= 50) return '🟡';
  return '🔴';
}

/**
 * Single-line summary for the Actions log (step title area).
 */
export function formatLogSummary(result: AuditResult): string {
  const emoji = overallEmoji(result.score);
  return `${emoji} Agent-readiness score: ${result.score}/100`;
}

/**
 * Multi-line group log printed inside a collapsible Actions group.
 */
export function formatLogDetail(result: AuditResult): string {
  const lines: string[] = [];

  lines.push('Category breakdown:');
  for (const cat of result.categories) {
    const bar = scoreEmoji(cat.score, cat.maxScore);
    lines.push(`  ${bar} ${cat.label}: ${cat.score}/${cat.maxScore}`);
    for (const f of cat.findings) {
      if (f.status !== 'pass') {
        const icon = STATUS_EMOJI[f.status] ?? '•';
        lines.push(`      ${icon} ${f.message}`);
      }
    }
  }

  if (result.missing.length > 0) {
    lines.push('');
    lines.push('Missing items:');
    for (const item of result.missing) {
      lines.push(`  • ${item}`);
    }
  }

  if (result.recommendations.length > 0) {
    lines.push('');
    lines.push('Recommendations:');
    for (const rec of result.recommendations) {
      lines.push(`  → ${rec}`);
    }
  }

  return lines.join('\n');
}

/**
 * Markdown body for the GitHub PR comment (without the marker line).
 */
export function formatMarkdownComment(result: AuditResult): string {
  const emoji = overallEmoji(result.score);
  const lines: string[] = [];

  lines.push(`## ${emoji} Agent Readiness Audit`);
  lines.push('');
  lines.push(`**Score: ${result.score} / 100**`);
  lines.push('');

  lines.push('### Category breakdown');
  lines.push('');
  lines.push('| Category | Score | Max |');
  lines.push('|----------|------:|----:|');
  for (const cat of result.categories) {
    const bar = scoreEmoji(cat.score, cat.maxScore);
    lines.push(`| ${bar} ${cat.label} | ${cat.score} | ${cat.maxScore} |`);
  }
  lines.push('');

  const failFindings = result.categories.flatMap((c) =>
    c.findings
      .filter((f) => f.status === 'fail' || f.status === 'warn')
      .map((f) => ({ category: c.label, finding: f })),
  );

  if (failFindings.length > 0) {
    lines.push('### Issues');
    lines.push('');
    for (const { category, finding } of failFindings.slice(0, 10)) {
      const icon = STATUS_EMOJI[finding.status] ?? '•';
      lines.push(`- ${icon} **${category}**: ${finding.message}`);
    }
    if (failFindings.length > 10) {
      lines.push(`- _…and ${failFindings.length - 10} more_`);
    }
    lines.push('');
  }

  if (result.missing.length > 0) {
    lines.push('### Top missing items');
    lines.push('');
    for (const item of result.missing.slice(0, 8)) {
      lines.push(`- \`${item}\``);
    }
    if (result.missing.length > 8) {
      lines.push(`- _…and ${result.missing.length - 8} more_`);
    }
    lines.push('');
  }

  if (result.recommendations.length > 0) {
    lines.push('### Recommendations');
    lines.push('');
    for (const rec of result.recommendations.slice(0, 6)) {
      lines.push(`1. ${rec}`);
    }
    if (result.recommendations.length > 6) {
      lines.push(`1. _…and ${result.recommendations.length - 6} more_`);
    }
    lines.push('');
  }

  lines.push(
    '_Generated by [agent-readiness-action](https://github.com/agent-readiness-kit/agent-readiness-action)_',
  );

  return lines.join('\n');
}
